#!/bin/bash

source ${OPENSHIFT_HOMEDIR}python/virtenv/venv/bin/activate

export PYTHON_EGG_CACHE=${OPENSHIFT_HOMEDIR}python/virtenv/venv/lib/python3.3/site-packages
export DJANGO_SETTINGS_MODULE=legendgen.settings

echo "Executing 'python ${OPENSHIFT_REPO_DIR}legendgen/manage.py syncdb --noinput'"
python "$OPENSHIFT_REPO_DIR"manage.py syncdb --noinput

echo "Executing 'django-admin.py collectstatic'"
django-admin.py collectstatic --noinput --settings=$DJANGO_SETTINGS_MODULE
